cart/urls.py
from django.urls import path
from .views import *


app_name = 'cart'

urlpatterns = [
    path('', CartDetailView.as_view(), name='cart_detail'),
    path('add/<int:product_id>/', CartAddView.as_view(), name='cart_add'),
    path('remove/<int:product_id>/', CartRemoveView.as_view(), name='cart_remove'),
]

heavyaura/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('user/', include('users.urls', namespace='user')),
    path('order/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('main.urls', namespace='main')),
    path('social-auth/', include('social_django.urls', namespace='social'))
] + debug_toolbar_urls() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *


app_name = 'main'

urlpatterns = [
    path('', PopularListView.as_view(), name='popular_list'),
    path('shop/', ProductListView.as_view(), name='product_list'),
    path('shop/<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('shop/category/<slug:category_slug>', ProductListView.as_view(), name='product_list_by_category'),
]

users/urls.py
from django.urls import path, reverse_lazy
from .views import UserLoginView, UserRegistrationView, UserProfileView, UserPasswordChange
from django.contrib.auth.views import LogoutView
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

app_name = 'user'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='user:login'), name="logout"),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('profile/', UserProfileView.as_view(), name='profile'),

    path('password-change/', UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),

    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('user:password_reset_done')
    ),
         name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('user:password_reset_complete')
    ),
         name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_image', blank=True,
                              null=True)
    
    class Meta:
        db_table = 'user'
    

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm, PasswordChangeForm
from .models import User
from django.contrib.auth import get_user_model


class UserLoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class UserRegistrationFrom(UserCreationForm):
    username = forms.CharField(label='Логин')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = [
            'first_name',
            'last_name',
            'email',
            'username',
            'password1',
            'password2',
        ]

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Такой Email уже существует')
        return email

class ProfileForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = [
            'image',
            'first_name',
            'last_name',
            'username',
            'email',
        ]
    
        image = forms.ImageField(required=False)
        first_name = forms.CharField()
        last_name = forms.CharField()
        username = forms.CharField()
        email = forms.CharField()


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля",
                                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))

users/views.py
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.views.generic import CreateView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages
from django.shortcuts import redirect
from .forms import UserLoginForm, UserRegistrationFrom, ProfileForm, UserPasswordChangeForm
from orders.models import Order, OrderItem
from django.db.models import Prefetch


class UserLoginView(LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('main:product_list')


class UserRegistrationView(CreateView):
    template_name = 'users/registration.html'
    form_class = UserRegistrationFrom
    success_url = reverse_lazy('user:login')

    
class UserProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'users/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ProfileForm(instance=self.request.user)

        # Заказы пользователя
        context['orders'] = Order.objects.filter(user=self.request.user).prefetch_related(
            Prefetch(
                'items',
                queryset=OrderItem.objects.select_related('product')
            )
        ).order_by('-id')
        return context

    def post(self, request, *args, **kwargs):
        form = ProfileForm(request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile was changed')
            return redirect(reverse_lazy('user:profile'))
        else:
            # Если форма невалидна, передаем её в контекст
            context = self.get_context_data()
            context['form'] = form
            return self.render_to_response(context)


class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy('users:password_change_done')
    template_name = 'users/password_change_form.html'

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login{% endblock title %}

{% block content %}
    <section class="login d-flex">
        <div class="login-title">
            <h2>Login</h2>
            <form action="{% url "user:login" %}" method="post">
                {% csrf_token %}
                {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
                <div class="mb-3">
                    <label for="id_username" class="form-label form-style">Username</label>
                    <input type="text" class="form-control form-style"
                    value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                    name="username" id="id_username" placeholder="Input username" required>
                </div>
                <div class="mb-3">
                    <label for="id_password" class="form-label form-style">Password</label>
                    <input type="password" class="form-control form-style"
                    name="password" id="id_password" placeholder="Your password" required>
                </div>
                <button type="submit" class="login-btn form-style">Login</button>
            </form>
            <div class="reset-pass">
                <hr>
                <div class="mt-3">
                    <a href="{% url "user:password_reset" %}">Reset Password</a> | <a href="{% url "user:registration" %}">Create Account</a>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

users/templates/users/password_change_done.html
{% extends 'base.html' %}
 
{% block content %}
<h1>Пароль успешно изменен!</h1>
 
<p >Вы успешно изменили пароль. <a href="{% url 'user:profile' %}">Вернуться в профиль.</a></p>
{% endblock %}

users/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Изменение пароля</h1>

<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p ><button type="submit">Изменить пароль</button></p>
</form>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "base.html" %}

{% block content %}
<h1>Пароль изменен</h1>

<p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
<a href="{% url 'user:login' %}">входа в систему</a>.</p>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<h1>Новый пароль</h1>

<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p ><button type="submit">Сохранить</button></p>
</form>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h1>Сброс пароля</h1>

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Восстановление пароля</h1>

<form method="post">
    {% csrf_token %}
{% for f in form %}
<p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <p ><button type="submit">Сбросить по E-mail</button></p>
</form>

{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Profile{% endblock title %}

{% block content %}
    <div class="d-flex">
        <div class="windowp d-flex bg-white p-4 mb-4 mx-2 rounded">
            <form action="{% url "user:profile" %}" method="post" enctype="multipart/form-data">
                <h2 class="mb-2">Profile</h2>
                {% csrf_token %}
                <div class="d-flex">
                    <div class="1box">
                        <div class="col-md-12 mb-3">
                            {% if user.image %}
                                <img src="{{ user.image.url }}" alt="Avatar" class="img-fluid"
                                style="max-width: 150px; max-height: 150px;">
                            {% else %}
                                <img src="{% static 'img/noimage.jpg' %}" alt="Avatar" class="img-fluid"
                                style="max-width: 150px; max-height: 150px;">
                            {% endif %}
                            <input type="file" class="form-control form-styleprofile mt-2" id="id_image"
                            name="image" accept="image/*">
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="id_first_name" class="form-label">First Name</label>
                            <input type="text" class="form-control form-styleprofile" id="id_first_name"
                            name="first_name" placeholder="Your First Name" value="{{ form.first_name.value }}"
                            required>
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="id_last_name" class="form-label">Last Name</label>
                            <input type="text" class="form-control form-styleprofile" id="id_last_name"
                            name="last_name" placeholder="Your Last Name" value="{{ form.last_name.value }}"
                            required>
                        </div>
                    </div>
                    <div class="box2">
                        <div class="col-md-12 mb-3">
                            <label for="id_username" class="form-label">Username</label>
                            <input type="text" class="form-control form-styleprofile" id="id_username"
                            name="username" placeholder="Your Username" value="{{ form.username.value }}"
                            required>
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="id_email" class="form-label">Email</label>
                            <input type="email" class="form-control form-styleprofile" id="id_email"
                            name="email" placeholder="Your Email" value="{{ form.email.value }}"
                            required>
                        </div>
                    </div>
                </div>
                <div class="btns d-flex gap-4 mt-4">
                    <button type="submit" class="profile-btn">Save</button>
                </div>
            </form>
            <form method="POST" action="{% url 'user:logout' %}">
                {% csrf_token %}
                <button type="submit" class="profile-btn">Logout</button>
            </form>
            <div class="orders">
                <h2 class="mb-2">Your Orders</h2>   
                {% if orders %}
                    <div class="orderss">
                        {% for order in orders %}
                            <div class="order-cart">
                                <h5 class="order-title">Order № {{ order.id }}</h5>
                                <p class="order-desc">
                                    {% for item in order.items.all %}
                                        <div class="orders-carts">
                                            <span class="dadad">Name: </span><a class="" href="{% url 'main:product_detail' item.product.slug %}">{{ item.product.name }}</a>
                                            <br>
                                            <span class="dadad">Quantity:</span> {{ item.quantity }},
                                            <span class="dadad">Price: $ {{ item.price }}</span> <br>
                                            <span class="dadad">Date:</span>  {{ order.created }}
                                            <br>
                                        </div>
                                    {% endfor %}
                                </p>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    <h4 class="notorders">You haven't ordered anything yet.</h4>
                {% endif %}         
            </div>
        </div>
{% endblock content %}

users/templates/users/registration.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Registration{% endblock title %}

{% block content %}
    <section class="login-reg d-flex">
        <div class="login-title">
            <h2>Registration</h2>
            <form action="{% url "user:registration" %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="id_first_name" class="form-label form-stylereg">First Name</label>
                        <input type="text" class="form-control form-stylereg" id="id_first_name"
                        value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                        name="first_name" placeholder="Your First Name" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="id_last_name" class="form-label form-stylereg">Last Name</label>
                        <input type="text" class="form-control form-stylereg" id="id_last_name"
                        value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                        name="last_name" placeholder="Your Last Name" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="id_username" class="form-label form-stylereg">Username</label>
                        <input type="text" class="form-control form-stylereg" id="id_username"
                        value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                        name="username" placeholder="Your Username" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="id_email" class="form-label form-stylereg">Email</label>
                        <input type="email" class="form-control form-stylereg" id="id_email"
                        value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                        name="email" placeholder="Your Email" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="id_password1" class="form-label form-stylereg">Password</label>
                        <input type="password" class="form-control form-stylereg" id="id_password1"
                        value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                        name="password1" placeholder="Your Password" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="id_password2" class="form-label form-stylereg">Confirm Password</label>
                        <input type="password" class="form-control form-stylereg" id="id_password2"
                        value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                        name="password2" placeholder="Your Password" required>
                    </div>
                    {% for f in form %}
                    <div class="form-error">{{ f.errors }}</div>
                    {% endfor %}
                </div>
                <button type="submit" class="login-btn form-style">Register</button>
            </form>
        </div>
    </section>
{% endblock content %}